(() => {
  'use strict';
  const MEMBERS=['Gagan','Teja Swaroop','Chinmayee','Deepika','Geetha','Sinchana','Gangaraju','Ganesh','Girish','Gagana','Gangothri','Prabhakar','Kushanth'];
  const TOOLS={
    'graphic-design':['✦','Graphic Design','Design and brand workspace',['Canva','Adobe Express','Figma','Photopea','Unsplash','Google Fonts','Noun Project']],
    'ai-tools':['✧','AI Tools','Launch AI assistants in a dedicated workspace',['ChatGPT','Gemini','Claude','Microsoft Copilot','Perplexity']],
    'social-media':['◎','Social Media','Social platform hub and notifications',['WhatsApp','Instagram','WhatsApp Channel','YouTube','Pinterest','Facebook','LinkedIn','Telegram','X']],
    'video-tools':['▶','Video Tools','Video editing and review workspace',['CapCut','Alight Motion','VN','Clipchamp','OpenShot','DaVinci Resolve','VSDC Free Video Editor']],
    'image-tools':['▧','Image Tools','Image editing and enhancement workspace',['Adobe Express','Photo Editor','Microsoft Photos','Microsoft Clipchamp','Photoshop']],
    'document-tools':['▤','Documents','Documentation and collaboration workspace',['GitBook','Mintlify','Confluence','Notion']],
    'pdf-tools':['PDF','PDF Tools','PDF creation and editing workspace',['PDFgear','PDF24 Creator','Foxit PDF Reader','Microsoft Edge','Adobe Acrobat Online Editor']],
    'productivity-tools':['✓','Productivity','Tasks, notes and focus workspace',['Task Manager','Notes','To-do List','Pomodoro','Time Tracker']],
    'developer-tools':['</>','Developer Tools','Code and development workspace',['VS Code','CodePen','Lovable','Rocket','Claude Code']],
    'business-tools':['₹','Business Tools','Business operations workspace',['Invoice Builder','Quotation','CRM','Budget Planner']],
    'education-tools':['⌘','Education Tools','Courses, notes and quizzes',['Online Courses','Study Notes','Quiz','Flashcards','Research']],
    'entertainment-tools':['🎮','Entertainment','Games and media workspace',['Games','Music Search','Movie Search','Live TV','Streaming']],
    'utilities-tools':['⚡','Utilities','Everyday utility workspace',['Calculator','Unit Converter','Text Tools','QR Generator','Color Picker']],
    'music':['♫','Music Player','Music and playlist workspace',['Spotify','JioSaavn','YouTube Music','Apple Music','Amazon Music']]
  };
  const APP_URLS={
    'Canva':'https://www.canva.com/','Adobe Express':'https://www.adobe.com/express/','Figma':'https://www.figma.com/','Photopea':'https://www.photopea.com/','Unsplash':'https://unsplash.com/','Google Fonts':'https://fonts.google.com/','Noun Project':'https://thenounproject.com/',
    'ChatGPT':'https://chatgpt.com/','Gemini':'https://gemini.google.com/','Claude':'https://claude.ai/','Microsoft Copilot':'https://copilot.microsoft.com/','Perplexity':'https://www.perplexity.ai/',
    'WhatsApp':'https://web.whatsapp.com/','Instagram':'https://www.instagram.com/','WhatsApp Channel':'https://www.whatsapp.com/','YouTube':'https://studio.youtube.com/','Pinterest':'https://www.pinterest.com/','Facebook':'https://www.facebook.com/','LinkedIn':'https://www.linkedin.com/','Telegram':'https://web.telegram.org/','X':'https://x.com/',
    'CapCut':'https://www.capcut.com/','Alight Motion':'https://alightmotion.com/','VN':'https://www.vlognow.me/','Clipchamp':'https://clipchamp.com/','OpenShot':'https://www.openshot.org/','DaVinci Resolve':'https://www.blackmagicdesign.com/products/davinciresolve','VSDC Free Video Editor':'https://www.videosoftdev.com/free-video-editor',
    'GitBook':'https://www.gitbook.com/','Mintlify':'https://www.mintlify.com/','Confluence':'https://www.atlassian.com/software/confluence','Notion':'https://www.notion.so/',
    'PDFgear':'https://www.pdfgear.com/','PDF24 Creator':'https://tools.pdf24.org/','Foxit PDF Reader':'https://www.foxit.com/pdf-reader/','Microsoft Edge':'https://www.microsoft.com/edge','Adobe Acrobat Online Editor':'https://www.adobe.com/acrobat/online.html',
    'VS Code':'https://code.visualstudio.com/','CodePen':'https://codepen.io/','Lovable':'https://lovable.dev/','Rocket':'https://rocket.new/','Claude Code':'https://claude.ai/code',
    'Spotify':'https://play.spotify.com/','JioSaavn':'https://www.jiosaavn.com/','YouTube Music':'https://music.youtube.com/','Apple Music':'https://music.apple.com/','Amazon Music':'https://music.amazon.com/'
  };
  const STORAGE='srsVisionProductionStateV1', SETTINGS='srsVisionProductionSettingsV1';
  const defaultProjects=[
    {id:1,name:'Brand Identity',client:'Nova Tech',progress:80,status:'In Progress',due:'2026-10-02',value:28000,member:'Gagan',tool:'graphic-design',prompt:'Create the brand identity and final presentation.'},
    {id:2,name:'Social Media Creative',client:'Bright Mart',progress:60,status:'Planning',due:'2026-10-05',value:16000,member:'Chinmayee',tool:'social-media',prompt:'Prepare the social media creative pack.'},
    {id:3,name:'Poster Design',client:'Green Earth',progress:40,status:'In Progress',due:'2026-10-12',value:9000,member:'Deepika',tool:'graphic-design',prompt:'Design a clean promotional poster.'},
    {id:4,name:'Packaging Design',client:'Organic Foods',progress:20,status:'Pending',due:'2026-10-20',value:22000,member:'Gangothri',tool:'graphic-design',prompt:'Create packaging concepts and production files.'}
  ];
  const makeInitial=()=>({
    projects:defaultProjects.map(x=>({...x})),
    team:{name:'SRS VISION',members:MEMBERS.map((name,i)=>({id:'m'+(i+1),name,role:'Team Member',service:'',phone:'',skills:'',notes:''}))},
    tasks:[{id:1,title:'Prepare brand review',member:'Gagan',tool:'graphic-design',project:1,prompt:'Prepare the first brand review.',status:'In Progress',created:new Date().toISOString()}],
    assignments:[],notifications:[{id:1,title:'Welcome to SRS Vision',body:'Your shared workspace is ready.',time:new Date().toISOString(),read:false}],
    files:[],notes:[],calendar:[{id:1,title:'Client Review',date:'2026-10-02',time:'11:00',type:'Meeting'},{id:2,title:'Poster Delivery',date:'2026-10-12',time:'15:00',type:'Deadline'}],
    finance:{accounts:[{id:'main',name:'SRS Vision Main Account',type:'Business',balance:0},{id:'operations',name:'Operations Account',type:'Business',balance:0}],transactions:[],transfers:[]},
    workspaces:{},apps:{},music:{playlist:[]},settings:{company:'SRS VISION',quote:'Great stories are not just filmed, they are designed.'}
  });
  const clone=x=>JSON.parse(JSON.stringify(x));
  function loadState(){try{const raw=JSON.parse(localStorage.getItem(STORAGE)||'null');if(!raw)return makeInitial();const base=makeInitial();const s={...base,...raw};s.team={...base.team,...raw.team,members:Array.isArray(raw.team?.members)?raw.team.members:base.team.members};s.projects=Array.isArray(raw.projects)?raw.projects:base.projects;s.tasks=Array.isArray(raw.tasks)?raw.tasks:[];s.assignments=Array.isArray(raw.assignments)?raw.assignments:[];s.notifications=Array.isArray(raw.notifications)?raw.notifications:[];s.files=Array.isArray(raw.files)?raw.files:[];s.calendar=Array.isArray(raw.calendar)?raw.calendar:base.calendar;s.finance={...base.finance,...raw.finance,accounts:Array.isArray(raw.finance?.accounts)?raw.finance.accounts:base.finance.accounts,transactions:Array.isArray(raw.finance?.transactions)?raw.finance.transactions:[],transfers:Array.isArray(raw.finance?.transfers)?raw.finance.transfers:[]};s.apps=raw.apps&&typeof raw.apps==='object'?raw.apps:{};s.workspaces=raw.workspaces&&typeof raw.workspaces==='object'?raw.workspaces:{};s.music={...base.music,...raw.music,playlist:Array.isArray(raw.music?.playlist)?raw.music.playlist:[]};s.settings={...base.settings,...raw.settings};return s}catch{return makeInitial()}}
  let state=loadState();let route=location.hash.slice(1)||'dashboard';let activeTaskId=null;let toastTimer;
  const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const money=n=>'₹ '+Number(n||0).toLocaleString('en-IN');const initials=n=>n.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();
  function saveLocal(){localStorage.setItem(STORAGE,JSON.stringify(state));localStorage.setItem('srsVisionLastLocalSave',new Date().toISOString())}
  let saveTimer;function persist(){saveLocal();clearTimeout(saveTimer);saveTimer=setTimeout(()=>Live.write(),350)}
  function notify(m){const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
  function saveWorkspace(k,partial){state.workspaces[k]={...(state.workspaces[k]||{}),...partial,updatedAt:new Date().toISOString()};persist();renderRoute(false)}
  function toolRoute(k){return TOOLS[k]?k:'dashboard'}
  function pushRoute(r){route=r;history.pushState({route:r},'',`#${r}`);renderShell();renderRoute(false)}
  function replaceRoute(r){route=r;history.replaceState({route:r},'',`#${r}`);renderShell();renderRoute(false)}
  function shellNav(){
    const main=[['dashboard','⌂','Dashboard'],['projects','▣','Projects'],['team','♧','Teams'],['calendar','📅','Calendar'],['reports','▥','Reports']];
    const work=[['files','📁','Files'],['work','◉','Work Queue'],['notifications','🔔','Notifications'],['money-transfer','💸','Money'],['banking','🏦','Banking'],['accounts','₹','Accounts'],['settings','⚙','Settings']];
    const tools=Object.entries(TOOLS).map(([r,v])=>[r,v[0],v[1]]);
    return `<aside class="sidebar"><div class="brand"><img src="srs-vision-logo.png"><div><h1>SRS VISION</h1><small>YOUR VISION • OUR CREATION</small></div></div><div class="navgroup"><div class="navlabel">Main</div>${main.map(n=>nav(n)).join('')}</div><div class="navgroup"><div class="navlabel">Tools</div>${tools.map(n=>nav(n)).join('')}</div><div class="navgroup"><div class="navlabel">Management</div>${work.map(n=>nav(n)).join('')}</div><div class="sideQuote"><strong>${esc(state.settings.quote||'Create. Share. Grow.')} </strong><span></span></div><div class="sideBottom">${nav(['database','◉','Live Database'])}</div></aside>`;
  }
  function nav([r,i,l]){return `<button class="navitem ${route===r?'active':''}" data-nav="${r}"><span class="icon">${i}</span><span>${esc(l)}</span></button>`}
  function topNav(){return `<header class="topbar"><div class="topbrand"><img src="srs-vision-logo.png"><b>SRS VISION</b></div><nav class="topnav"><button data-nav="dashboard">⌂</button><button data-nav="projects">Projects</button><button data-nav="team">Teams</button><button data-nav="calendar">Calendar</button><button data-nav="reports">Reports</button></nav><div class="search"><span>⌕</span><input id="globalSearch" placeholder="Search projects, members, tools…"></div><div class="topactions"><button class="btn" data-nav="notifications">🔔</button><button class="status" data-nav="database" id="dbStatus"><span class="dot"></span><span><b>Local</b><small>Browser storage</small></span></button><div class="user"><span class="avatar">SV</span><div><b>SRS Vision</b><small>Team Workspace</small></div></div></div></header>`}
  function renderShell(){document.body.className='';$('#app').innerHTML=`<div class="app">${shellNav()}<main class="mainwrap">${topNav()}<div class="content" id="content"></div></main></div><nav class="mobileNav"><button data-nav="dashboard">⌂<br>Home</button><button data-nav="projects">▣<br>Projects</button><button data-nav="team">♧<br>Team</button><button data-nav="work">◉<br>Work</button><button data-nav="tools-hub">✦<br>Tools</button></nav>`;renderStatus();}
  function renderStatus(){const e=$('#dbStatus');if(!e)return;const cls=Live.status==='online'?'live':Live.status==='error'?'err':'dot';const label=Live.status==='online'?'Live Database':Live.status==='error'?'Local Mode':'Local';const sub=Live.status==='online'?'Realtime ON':Live.detail||'Auto-save enabled';e.innerHTML=`<span class="dot ${cls}"></span><span><b>${label}</b><small>${esc(sub)}</small></span>`}
  function backButton(){return `<button class="btn ghost" data-back>← Back</button>`}
  function header(title,sub,actions=''){return `<div class="pageHead"><div><div class="eyebrow">SRS VISION · ${esc(title).toUpperCase()}</div><div class="title">${esc(title)}</div><div class="subtitle">${esc(sub)}</div></div><div class="heroActions">${backButton()}<button class="btn" data-nav="dashboard">Main Dashboard</button>${actions}</div></div>`}
  function renderMain(){
    const p=state.projects,a=p.filter(x=>x.status!=='Completed').length,c=p.filter(x=>x.status==='Completed').length,val=p.reduce((s,x)=>s+Number(x.value||0),0),income=state.finance.transactions.filter(x=>x.kind==='income').reduce((s,x)=>s+Number(x.amount||0),0),expense=state.finance.transactions.filter(x=>x.kind==='expense').reduce((s,x)=>s+Number(x.amount||0),0),profit=income-expense;
    const recent=p.slice(0,5).map((x,i)=>`<div class="projectRow"><div class="thumb">${['BD','SM','PD','PK','GD'][i%5]}</div><div><div class="projectName">${esc(x.name)}</div><div class="projectSub">${esc(x.client)} · ${esc(x.member)}</div></div><div><div class="bar"><i style="width:${Math.max(0,Math.min(100,Number(x.progress||0)))}%"></i></div><div class="projectSub">${Number(x.progress||0)}%</div></div><span class="pill ${x.status==='Completed'?'done':x.status==='Planning'?'planning':x.status==='Pending'?'pending':'progress'}">${esc(x.status)}</span><button class="btn small" data-edit-project="${p.indexOf(x)}">⋮</button></div>`).join('');
    const people=state.team.members.slice(0,8).map(m=>`<span class="tinyA" title="${esc(m.name)}">${initials(m.name)}</span>`).join('');const events=state.calendar.slice(0,4).map(e=>`<div class="event"><b>${esc(e.title)}</b><small>${esc(e.date)} · ${esc(e.time||'')}</small></div>`).join('')||'<div class="empty">No calendar events yet.</div>';
    const bars=[42,58,68,54,76,88].map((v,i)=>`<div class="chartBar"><i style="height:${v}%"></i><span>${['Apr','May','Jun','Jul','Aug','Sep'][i]}</span></div>`).join('');
    const act=[['✦','Project activity',`${p.length} projects / ${a} active`],['♧','Team',`${state.team.members.length} SRS Vision members`],['◉','Saved work',`${state.tasks.length} tasks in Work Queue`],['♫','Music',`${state.music.playlist.length} local tracks`],['🔔','Notifications',`${state.notifications.filter(n=>!n.read).length} unread`]].map(x=>`<div class="activityItem"><span class="aicon">${x[0]}</span><div><b>${x[1]}</b><small>${esc(x[2])}</small></div></div>`).join('');
    const tools=Object.entries(TOOLS).map(([r,v])=>`<button class="toolSlot" data-nav="${r}"><div class="toolIcon">${v[0]}</div><b>${esc(v[1])}</b><small>${esc(v[2])}</small></button>`).join('');
    $('#content').innerHTML=`<section class="heroImage"><div class="heroOverlay"><div class="heroBrand"><img src="srs-vision-logo.png" alt="SRS Vision logo"><div><div class="eyebrow">SRS VISION · MAIN DASHBOARD</div><h2>Good Evening,<br><span>SRS Vision</span></h2></div></div><p>Your creative operations at a glance</p><div class="heroActions"><button class="btn primary" data-nav="projects">Open Projects</button><button class="btn cyan" data-nav="work">Work Queue</button><button class="btn" data-nav="team">View Team</button></div></div></section>
    <section class="kpis"><div class="kpi"><div class="kpiTop"><span>Total Projects</span><span>▣</span></div><b>${p.length}</b><span class="trend">↑ ${a} active</span><div class="hint">saved automatically</div></div><div class="kpi"><div class="kpiTop"><span>Team Members</span><span>♧</span></div><b>${state.team.members.length}</b><span class="trend">SRS Vision</span><div class="hint">single team</div></div><div class="kpi"><div class="kpiTop"><span>Active Work</span><span>✓</span></div><b>${state.tasks.filter(t=>t.status!=='Done').length}</b><span class="trend">${state.tasks.filter(t=>t.status==='Done').length} done</span><div class="hint">continue saved work</div></div><div class="kpi"><div class="kpiTop"><span>Profit / Loss</span><span>₹</span></div><b class="${profit>=0?'pos':'neg'}">${money(profit)}</b><span class="trend">Income ${money(income)}</span><div class="hint">Expense ${money(expense)}</div></div></section>
    <div class="grid3"><section class="panel"><div class="panelHead"><h3>Recent Projects</h3><button class="btn small" data-nav="projects">View All →</button></div><div class="panelBody">${recent||'<div class="empty">No projects yet.</div>'}</div></section><section class="panel"><div class="panelHead"><h3>Team Overview</h3><button class="btn small" data-nav="team">View All →</button></div><div class="panelBody"><div class="teamCard"><div class="teamTop"><b>${esc(state.team.name)}</b><strong>${state.team.members.length}</strong></div><div class="projectSub">All members belong to one SRS Vision team.</div><div class="people">${people}</div></div><div class="meta"><span class="chip">${state.team.members.length} Members</span><span class="chip">Editable</span><span class="chip">Realtime Ready</span></div></div></section><section class="panel"><div class="panelHead"><h3>Recent Activity</h3><button class="btn small" data-nav="notifications">View All →</button></div><div class="panelBody">${act}</div></section></div>
    <div class="grid2"><section class="panel"><div class="panelHead"><h3>Calendar</h3><button class="btn small" data-nav="calendar">Open →</button></div><div class="panelBody calendar"><div class="calgrid">${['S','M','T','W','T','F','S'].map(x=>`<div class="calday head">${x}</div>`).join('')}${Array.from({length:35},(_,i)=>`<div class="calday ${i===18?'today':''}">${(i%30)+1}</div>`).join('')}</div><div><div class="eyebrow">UPCOMING</div><div class="events" style="margin-top:9px">${events}</div></div></div></section><section class="panel"><div class="panelHead"><h3>Reports</h3><button class="btn small" data-nav="reports">Open Reports →</button></div><div class="panelBody"><div class="donutWrap"><div class="donut"><div class="donutLabel"><div><b>${p.length}</b><small>Total Projects</small></div></div></div><div class="legend"><div class="legendRow"><span><i class="dotL" style="background:#15d7ff"></i>Active</span><b>${a}</b></div><div class="legendRow"><span><i class="dotL" style="background:#7e4cff"></i>Completed</span><b>${c}</b></div><div class="legendRow"><span><i class="dotL" style="background:#ffd15a"></i>Pending</span><b>${p.filter(x=>x.status==='Pending').length}</b></div><div class="legendRow"><span><i class="dotL" style="background:#ef4fc8"></i>Planning</span><b>${p.filter(x=>x.status==='Planning').length}</b></div></div></div><div class="chart">${bars}</div></div></section></div>
    <div class="grid2"><section class="panel"><div class="panelHead"><h3>Work Queue / Task Bar</h3><button class="btn small" data-nav="work">Open Queue →</button></div><div class="panelBody">${state.tasks.slice(0,4).map(t=>`<div class="workCard ${t.status==='In Progress'?'started':''}"><div class="workTop"><div><div class="workTitle">${esc(t.title)}</div><div class="projectSub">${esc(t.member)} · ${esc(t.tool)} · ${t.status}</div></div><button class="btn small" data-start-task="${t.id}">${t.status==='Done'?'Done':'Start'}</button></div></div>`).join('')||'<div class="empty">No assigned work.</div>'}</div></section><section class="quoteCard"><div><strong>${esc(state.settings.quote)}</strong><small>— SRS VISION · YOUR VISION • OUR CREATION</small></div></section></div>
    <section class="panel" style="margin-top:14px"><div class="panelHead"><h3>Tool Slots</h3><span class="subtitle">Each tool opens its own dedicated dashboard</span></div><div class="panelBody"><div class="toolGrid">${tools}</div></div></section>`;
  }
  function renderTeam(){const cards=state.team.members.map((m,i)=>`<article class="member"><div class="memberHead"><div class="memberAvatar">${initials(m.name)}</div><div><h4>${esc(m.name)}</h4><small>${esc(m.role||'Team Member')}</small></div></div><div class="projectSub">${esc(m.service||'SRS Vision Member')}</div><div class="projectSub">${esc(m.skills||'')}</div><div class="memberActions"><button class="btn primary" data-member-edit="${i}">Edit</button><button class="btn" data-member-custom="${i}">Custom</button><button class="btn danger" data-member-delete="${i}">Remove</button></div></article>`).join('');$('#content').innerHTML=header('Teams & Members','One shared SRS Vision team with all members.','<button class="btn primary" data-add-member>＋ Add Member</button>')+`<div class="meta"><span class="chip">${state.team.members.length} Members</span><span class="chip">One Team: SRS VISION</span><span class="chip">Auto-saved</span></div><section class="panel"><div class="panelHead"><h3>All SRS Vision Members</h3></div><div class="panelBody"><div class="members">${cards}</div></div></section>`}
  function editMember(i){const m=state.team.members[i];openModal(`Edit ${m.name}`,`<div class="modalGrid"><div class="field"><label>Name</label><input class="input" id="mName" value="${esc(m.name)}"></div><div class="field"><label>Role</label><input class="input" id="mRole" value="${esc(m.role)}"></div><div class="field"><label>Service</label><input class="input" id="mService" value="${esc(m.service)}"></div><div class="field"><label>Phone</label><input class="input" id="mPhone" value="${esc(m.phone)}"></div><div class="field"><label>Skills</label><input class="input" id="mSkills" value="${esc(m.skills)}"></div><div class="field"><label>Notes</label><input class="input" id="mNotes" value="${esc(m.notes)}"></div></div>`,()=>{m.name=$('#mName').value.trim()||m.name;m.role=$('#mRole').value.trim()||'Team Member';m.service=$('#mService').value.trim();m.phone=$('#mPhone').value.trim();m.skills=$('#mSkills').value.trim();m.notes=$('#mNotes').value.trim();persist();closeModal();renderRoute(false);notify('Member updated and saved')})}
  function renderProjects(){const rows=state.projects.map((p,i)=>`<div class="trow"><div><b>${esc(p.name)}</b><div class="projectSub">${esc(p.client)}</div></div><div>${esc(p.member)}</div><div>${esc(p.status)}</div><div><div class="bar"><i style="width:${Math.max(0,Math.min(100,p.progress))}%"></i></div><div class="projectSub">${p.progress}% · ${esc(p.tool)}</div></div><div class="heroActions"><button class="btn small" data-edit-project="${i}">Edit</button><button class="btn small cyan" data-assign-project="${i}">Assign</button><button class="btn small" data-share-project="${i}">Share</button><button class="btn small green" data-continue-project="${i}">Continue</button></div></div>`).join('');$('#content').innerHTML=header('Projects','Projects are stored locally immediately and synced to Supabase when available.','<button class="btn primary" data-add-project>＋ New Project</button>')+`<section class="panel"><div class="panelBody"><div class="table"><div class="trow thead"><div>Project</div><div>Assigned Member</div><div>Status</div><div>Progress / Tool</div><div>Actions</div></div>${rows||'<div class="empty">No projects.</div>'}</div></div></section><section class="panel" style="margin-top:12px"><div class="panelHead"><h3>Saved project files & progress</h3><span class="autosave">Every change is auto-saved</span></div><div class="panelBody"><div class="meta"><span class="chip">${state.files.length} saved files</span><span class="chip">${state.assignments.length} assignments</span><span class="chip">${state.tasks.length} work items</span></div></div></section>`}
  function projectModal(i=-1,assignOnly=false){const p=i>=0?state.projects[i]:{name:'',client:'',progress:0,status:'Planning',due:'',value:0,member:MEMBERS[0],tool:'graphic-design',prompt:''};openModal(assignOnly?'Assign Project':'New / Edit Project',`<div class="modalGrid"><div class="field"><label>Project</label><input class="input" id="pName" value="${esc(p.name)}"></div><div class="field"><label>Client</label><input class="input" id="pClient" value="${esc(p.client)}"></div><div class="field"><label>Progress</label><input class="input" id="pProgress" type="number" min="0" max="100" value="${p.progress}"></div><div class="field"><label>Status</label><select class="select" id="pStatus"><option>Planning</option><option>In Progress</option><option>Pending</option><option>Completed</option></select></div><div class="field"><label>Due Date</label><input class="input" id="pDue" type="date" value="${esc(p.due)}"></div><div class="field"><label>Value</label><input class="input" id="pValue" type="number" value="${p.value}"></div><div class="field"><label>Assign Member</label><select class="select" id="pMember">${MEMBERS.map(n=>`<option ${n===p.member?'selected':''}>${esc(n)}</option>`).join('')}</select></div><div class="field"><label>Tool Workspace</label><select class="select" id="pTool">${Object.entries(TOOLS).map(([r,v])=>`<option value="${r}" ${r===p.tool?'selected':''}>${esc(v[1])}</option>`).join('')}</select></div><div class="field" style="grid-column:1/-1"><label>Prompt / Work Instruction</label><textarea class="textarea" id="pPrompt">${esc(p.prompt||'')}</textarea></div></div>`,()=>{const obj={name:$('#pName').value.trim()||'Untitled Project',client:$('#pClient').value.trim(),progress:Number($('#pProgress').value||0),status:$('#pStatus').value,due:$('#pDue').value,value:Number($('#pValue').value||0),member:$('#pMember').value,tool:$('#pTool').value,prompt:$('#pPrompt').value.trim()};if(i<0){obj.id=Date.now();state.projects.unshift(obj)}else state.projects[i]={...state.projects[i],...obj};if(i>=0){const member=obj.member;state.tasks.unshift({id:Date.now()+1,title:`Work: ${obj.name}`,member,tool:obj.tool,project:i,prompt:obj.prompt,status:'Assigned',created:new Date().toISOString()});state.notifications.unshift({id:Date.now()+2,title:'Project assigned',body:`${obj.name} assigned to ${member}. Open Work Queue to start.`,time:new Date().toISOString(),read:false})}persist();closeModal();renderProjects();notify(i<0?'Project created and saved':'Project updated, assigned and saved')})}
  function shareProject(i){const p=state.projects[i];const msg=`SRS Vision Work\nProject: ${p.name}\nClient: ${p.client}\nAssigned: ${p.member}\nTool: ${TOOLS[p.tool]?.[1]||p.tool}\nPrompt: ${p.prompt||'Please start the assigned work.'}`;openModal('Share Assignment',`<div class="field"><label>Message</label><textarea class="textarea" id="shareMsg">${esc(msg)}</textarea></div><div class="heroActions"><button class="btn green" id="shareWa">Share on WhatsApp</button><button class="btn primary" id="shareMail">Share by Email</button></div><div class="assignBox">The website can open WhatsApp or the default email composer; it cannot bypass the external app's own login/permissions.</div>`,()=>{});$('#shareWa').onclick=()=>window.open('https://wa.me/?text='+encodeURIComponent($('#shareMsg').value),'_blank','noopener');$('#shareMail').onclick=()=>{location.href='mailto:?subject='+encodeURIComponent('SRS Vision Work: '+p.name)+'&body='+encodeURIComponent($('#shareMsg').value)}}
  function continueProject(i){const p=state.projects[i];const task={id:Date.now(),title:`Continue: ${p.name}`,member:p.member,tool:p.tool,project:i,prompt:p.prompt,status:'In Progress',created:new Date().toISOString()};state.tasks.unshift(task);state.notifications.unshift({id:Date.now()+1,title:'Work started',body:`${p.member} started ${p.name}.`,time:new Date().toISOString(),read:false});activeTaskId=task.id;persist();pushRoute(p.tool);notify('Saved project reopened — continue from your last state')}
  function renderCalendar(){const cells=Array.from({length:35},(_,i)=>`<div class="calday ${i===18?'today':''}">${(i%30)+1}</div>`).join('');const ev=state.calendar.map((e,i)=>`<div class="event"><b>${esc(e.title)}</b><small>${esc(e.date)} · ${esc(e.time||'')}</small><div class="heroActions"><button class="btn small" data-edit-event="${i}">Edit</button><button class="btn small danger" data-delete-event="${i}">Delete</button></div></div>`).join('');$('#content').innerHTML=header('Calendar','Events and scheduled work are saved automatically.','<button class="btn primary" data-add-event>＋ Add Event</button>')+`<section class="panel"><div class="panelBody calendar"><div class="calgrid">${['S','M','T','W','T','F','S'].map(x=>`<div class="calday head">${x}</div>`).join('')}${cells}</div><div class="events">${ev||'<div class="empty">No events.</div>'}</div></div></section>`}
  function renderReports(){const p=state.projects,completed=p.filter(x=>x.status==='Completed').length,active=p.length-completed,income=state.finance.transactions.filter(x=>x.kind==='income').reduce((s,x)=>s+Number(x.amount||0),0),expense=state.finance.transactions.filter(x=>x.kind==='expense').reduce((s,x)=>s+Number(x.amount||0),0),profit=income-expense,values=[32,49,44,65,58,78,86];const bars=values.map((v,i)=>`<div class="vcol"><i style="height:${v}%"></i><small>${['Apr','May','Jun','Jul','Aug','Sep','Oct'][i]}</small></div>`).join('');$('#content').innerHTML=header('Reports','Graphical work and financial reporting with separate profit/loss views.','<button class="btn primary" data-export-report>Export Report</button>')+`<div class="kpis"><div class="kpi"><span>Total Project Value</span><b>${money(p.reduce((s,x)=>s+Number(x.value||0),0))}</b><span class="trend">${p.length} projects</span></div><div class="kpi"><span>Income</span><b>${money(income)}</b><span class="trend">Revenue</span></div><div class="kpi"><span>Expenses</span><b>${money(expense)}</b><span class="hint">Tracked</span></div><div class="kpi"><span>Profit / Loss</span><b class="${profit>=0?'pos':'neg'}">${money(profit)}</b><span class="trend">${profit>=0?'Profit':'Loss'}</span></div></div><div class="graphGrid"><section class="graphBox"><h3>Work Performance</h3><div class="barChart">${bars}</div></section><section class="graphBox"><h3>Profit & Loss</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><div><div class="projectSub">Income</div><div class="profitValue pos">${money(income)}</div></div><div><div class="projectSub">Expenses</div><div class="profitValue neg">${money(expense)}</div></div></div><div class="assignBox"><b>Net: </b><span class="${profit>=0?'pos':'neg'}">${money(profit)}</span><br><small class="projectSub">Add income/expense entries from Accounts or Banking.</small></div></section></div><section class="panel" style="margin-top:12px"><div class="panelHead"><h3>Project status breakdown</h3></div><div class="panelBody"><div class="meta"><span class="chip">Active ${active}</span><span class="chip">Completed ${completed}</span><span class="chip">Pending ${p.filter(x=>x.status==='Pending').length}</span><span class="chip">Planning ${p.filter(x=>x.status==='Planning').length}</span></div></div></section>`}
  function renderWork(){const rows=state.tasks.map(t=>`<div class="workCard ${t.status==='In Progress'?'started':''}"><div class="workTop"><div><div class="workTitle">${esc(t.title)}</div><div class="projectSub">Assigned to <b>${esc(t.member)}</b> · ${esc(TOOLS[t.tool]?.[1]||t.tool)} · ${esc(t.status)}</div><div class="projectSub">Prompt: ${esc(t.prompt||'No prompt')}</div></div><div class="heroActions"><button class="btn small ${t.status==='Done'?'':'cyan'}" data-start-task="${t.id}">${t.status==='Done'?'Done':'Open & Start'}</button><button class="btn small" data-task-share="${t.id}">Share</button></div></div></div>`).join('');$('#content').innerHTML=header('Work Queue','Every assigned project becomes a saved task that can be continued without recreating it.','<button class="btn primary" data-assign-work>＋ Assign Work</button>')+`<section class="panel"><div class="panelHead"><h3>Assigned Work</h3><span class="autosave">Auto-save + restore enabled</span></div><div class="panelBody">${rows||'<div class="empty">No work assigned yet.</div>'}</div></section>`}
  function assignWork(){openModal('Assign Work / Project',`<div class="modalGrid"><div class="field"><label>Project</label><select class="select" id="awProject">${state.projects.map((p,i)=>`<option value="${i}">${esc(p.name)} — ${esc(p.client)}</option>`).join('')}</select></div><div class="field"><label>Member</label><select class="select" id="awMember">${MEMBERS.map(n=>`<option>${esc(n)}</option>`).join('')}</select></div><div class="field"><label>Tool</label><select class="select" id="awTool">${Object.entries(TOOLS).map(([r,v])=>`<option value="${r}">${esc(v[1])}</option>`).join('')}</select></div><div class="field"><label>Priority</label><select class="select" id="awPri"><option>High</option><option>Medium</option><option>Low</option></select></div><div class="field" style="grid-column:1/-1"><label>Prompt / Instructions</label><textarea class="textarea" id="awPrompt" placeholder="Give the exact work prompt for the selected member"></textarea></div></div>`,()=>{const pi=Number($('#awProject').value),p=state.projects[pi];const member=$('#awMember').value,tool=$('#awTool').value,prompt=$('#awPrompt').value.trim()||p.prompt||'Start the assigned work and save progress.';state.tasks.unshift({id:Date.now(),title:`${p.name} — ${$('#awPri').value}`,member,tool,project:pi,prompt,status:'Assigned',created:new Date().toISOString()});p.member=member;p.tool=tool;p.prompt=prompt;state.assignments.unshift({id:Date.now()+1,project:p.name,member,tool,prompt,time:new Date().toISOString()});state.notifications.unshift({id:Date.now()+2,title:'New work assigned',body:`${p.name} → ${member} using ${TOOLS[tool][1]}`,time:new Date().toISOString(),read:false});persist();closeModal();renderWork();notify(`Assigned to ${member}; notification created`)})}
  function startTask(id){const t=state.tasks.find(x=>x.id==id);if(!t)return;t.status='In Progress';activeTaskId=t.id;state.notifications.unshift({id:Date.now(),title:'Work started',body:`${t.member} started ${t.title}`,time:new Date().toISOString(),read:false});persist();pushRoute(t.tool)}
  function renderTool(key){const m=TOOLS[key];const ws=state.workspaces[key]||{};const assigned=activeTaskId?state.tasks.find(t=>t.id===activeTaskId):state.tasks.find(t=>t.tool===key&&t.status==='In Progress');const apps=(state.apps[key]||[]).map(a=>({name:a.name,url:a.url,custom:true}));const allApps=[...m[3].map(name=>({name,url:APP_URLS[name]||''})),...apps];
    let customUI='';if(key==='graphic-design')customUI=`<div class="wsGrid"><div><div class="field"><label>Design Title</label><input class="input autosaveInput" id="gdTitle" value="${esc(ws.title||'Your Vision')}"></div><div class="field"><label>Message</label><textarea class="textarea autosaveInput" id="gdBody">${esc(ws.body||'Create designs, posters, social creatives and brand stories.')}</textarea></div><div class="field"><label>Background</label><input class="input autosaveInput" id="gdBg" type="color" value="${esc(ws.bg||'#143d7a')}"></div><div class="heroActions"><button class="btn primary" id="gdExport">Download Design</button><button class="btn" id="gdClear">Reset</button></div><div class="autosave" id="wsSave">✓ Automatically saved</div></div><div class="editorCanvas" style="display:grid;place-items:center;min-height:300px;background:#03111f;border:1px solid #194a77;border-radius:14px"><div id="gdCanvas" style="width:90%;aspect-ratio:16/10;border-radius:12px;display:grid;place-items:center;text-align:center;padding:20px;background:${esc(ws.bg||'#143d7a')};box-shadow:0 20px 40px #0008"><div><h2 id="gdPreviewTitle" style="font-size:36px;margin:0 0 10px">${esc(ws.title||'Your Vision')}</h2><p id="gdPreviewBody">${esc(ws.body||'Create designs, posters, social creatives and brand stories.')}</p></div></div></div></div>`;
    else if(key==='image-tools')customUI=`<div class="wsGrid"><div><div class="field"><label>Upload Image</label><input class="input" id="imgFile" type="file" accept="image/*"></div><div class="field"><label>Filter</label><select class="select" id="imgFilter"><option value="none">Original</option><option value="grayscale(1)">Grayscale</option><option value="sepia(1)">Sepia</option><option value="contrast(1.3)">Contrast</option><option value="brightness(1.2)">Bright</option></select></div><div class="heroActions"><button class="btn primary" id="imgDownload">Download Image</button></div></div><div class="editorCanvas" style="min-height:300px;display:grid;place-items:center"><img id="imgPreview" alt="Preview" style="max-width:100%;max-height:320px;border-radius:12px;display:none"></div></div>`;
    else if(key==='video-tools')customUI=`<div class="wsGrid"><div><div class="field"><label>Video File</label><input class="input" id="videoFile" type="file" accept="video/*"></div><div class="field"><label>Playback Speed</label><select class="select" id="videoSpeed"><option>0.5</option><option selected>1</option><option>1.5</option><option>2</option></select></div><div class="autosave">Video work state is saved in this project; external editors open separately.</div></div><video id="videoPreview" controls style="width:100%;max-height:360px;background:#02060d;border-radius:12px"></video></div>`;
    else if(key==='document-tools'||key==='pdf-tools'||key==='developer-tools')customUI=`<div class="wsGrid"><div><div class="field"><label>Workspace Title</label><input class="input autosaveInput" id="wkTitle" value="${esc(ws.title||'Untitled Work')}"></div><div class="field"><label>Work Content</label><textarea class="textarea autosaveInput" id="wkBody">${esc(ws.body||'Start work here. This content is automatically saved.')}</textarea></div><div class="heroActions"><button class="btn primary" id="wkExport">Export Work</button><button class="btn" id="wkPrint">Print</button></div></div><div class="mutedBox"><b>Saved Work</b><p>Your changes are stored automatically. Close the site and reopen it later to continue from this saved state.</p><div class="autosave">✓ Auto-save enabled</div></div></div>`;
    else if(key==='music')customUI=musicEditor();
    else customUI=`<div class="workspaceCards">${m[3].map(name=>`<div class="miniTool"><b>${esc(name)}</b><small>Dedicated launcher</small><div class="heroActions"><button class="btn small primary" data-open-app="${esc(name)}" data-app-key="${esc(key)}">Open</button></div></div>`).join('')}</div><div class="workspace" style="margin-top:12px"><div class="field"><label>Workspace Notes</label><textarea class="textarea autosaveInput" id="wkBody" placeholder="Anything you write here is automatically saved…">${esc(ws.body||'')}</textarea></div><div class="autosave" id="wsSave">✓ Automatically saved</div></div>`;
    $('#content').innerHTML=header(m[1],m[2],`<button class="btn primary" data-add-app="${esc(key)}">＋ Add App</button>`)+`<section class="workspace"><div class="panelHead"><h3>Assigned Work</h3><span class="subtitle">${assigned?`Selected member: ${esc(assigned.member)} · ${esc(assigned.title)}`:'No active assignment'}</span></div>${assigned?`<div class="assignBox"><b>Prompt:</b> ${esc(assigned.prompt||'Start the task and save progress here.')}<div class="heroActions"><button class="btn green" data-complete-task="${assigned.id}">Mark Complete</button><button class="btn" data-task-share="${assigned.id}">Share Work</button></div></div>`:''}<div class="eyebrow" style="margin-top:14px">DEDICATED WORKSPACE</div><div style="font-size:20px;font-weight:900;margin-top:4px">${esc(m[1])}</div><div class="projectSub">Use the controls below; edits are saved automatically.</div><div style="margin-top:14px">${customUI}</div></section><section class="panel" style="margin-top:12px"><div class="panelHead"><h3>App Slots</h3><span class="subtitle">Direct launch</span></div><div class="panelBody"><div class="workspaceCards">${allApps.map(a=>`<div class="miniTool"><b>${esc(a.name)}</b>${a.custom?'<small>Custom app</small>':'<small>Official app</small>'}<div class="heroActions"><button class="btn small cyan" data-open-url="${esc(a.url)}">Open App</button>${a.custom?`<button class="btn small danger" data-remove-app="${esc(key)}" data-remove-name="${esc(a.name)}">Delete</button>`:''}</div></div>`).join('')}</div></div></section>`;
    bindTool(key);
  }
  function bindTool(key){
    $$('.autosaveInput').forEach(el=>el.addEventListener('input',()=>{saveWorkspace(key,{title:$('#wkTitle')?.value||state.workspaces[key]?.title||'',body:$('#wkBody')?.value||''});const s=$('#wsSave');if(s)s.textContent='✓ Saved just now'}));
    if(key==='graphic-design'){
      const update=()=>{const t=$('#gdTitle')?.value||'Your Vision',b=$('#gdBody')?.value||'',bg=$('#gdBg')?.value||'#143d7a';$('#gdPreviewTitle').textContent=t;$('#gdPreviewBody').textContent=b;$('#gdCanvas').style.background=bg;saveWorkspace(key,{title:t,body:b,bg})};$('#gdTitle')?.addEventListener('input',update);$('#gdBody')?.addEventListener('input',update);$('#gdBg')?.addEventListener('input',update);$('#gdExport')?.addEventListener('click',()=>downloadBlob(`SRS Vision\n${$('#gdTitle').value}\n\n${$('#gdBody').value}`,'text/plain','srs-vision-design.txt'));$('#gdClear')?.addEventListener('click',()=>{saveWorkspace(key,{title:'Your Vision',body:'Create designs, posters, social creatives and brand stories.',bg:'#143d7a'});renderRoute(false)})
    }
    if(key==='image-tools'){let current='';$('#imgFile')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;current=URL.createObjectURL(f);$('#imgPreview').src=current;$('#imgPreview').style.display='block';state.workspaces[key]={...(state.workspaces[key]||{}),filename:f.name};persist()});$('#imgFilter')?.addEventListener('change',e=>{$('#imgPreview').style.filter=e.target.value;state.workspaces[key]={...(state.workspaces[key]||{}),filter:e.target.value};persist()});$('#imgDownload')?.addEventListener('click',()=>{if(!$('#imgPreview').src)return notify('Choose an image first');const a=document.createElement('a');a.href=$('#imgPreview').src;a.download=state.workspaces[key]?.filename||'srs-vision-image';a.click()})}
    if(key==='video-tools'){let url='';$('#videoFile')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;url=URL.createObjectURL(f);$('#videoPreview').src=url;persist()});$('#videoSpeed')?.addEventListener('change',e=>{$('#videoPreview').playbackRate=Number(e.target.value);state.workspaces[key]={...(state.workspaces[key]||{}),speed:e.target.value};persist()})}
    if(key==='document-tools'||key==='pdf-tools'||key==='developer-tools'){const auto=()=>saveWorkspace(key,{title:$('#wkTitle').value,body:$('#wkBody').value});$('#wkTitle')?.addEventListener('input',auto);$('#wkBody')?.addEventListener('input',auto);$('#wkExport')?.addEventListener('click',()=>downloadBlob($('#wkBody').value,'text/plain',(($('#wkTitle').value||'srs-vision-work')+'.txt').replace(/\s+/g,'-')));$('#wkPrint')?.addEventListener('click',()=>printHtml($('#wkTitle').value||'SRS Vision Work',$('#wkBody').value))}
    if(key!=='graphic-design'&&key!=='image-tools'&&key!=='video-tools'&&key!=='document-tools'&&key!=='pdf-tools'&&key!=='developer-tools'&&key!=='music')$('#wkBody')?.addEventListener('input',()=>saveWorkspace(key,{body:$('#wkBody').value}))
  }
  function musicEditor(){const p=state.music.playlist;return `<div class="musicGrid"><div class="cover"><div class="record"></div></div><div class="player"><div class="field"><label>Add local audio</label><input class="input" id="musicFile" type="file" accept="audio/*" multiple></div><div class="trackName" id="trackName">${p[0]?esc(p[0].name):'SRS Vision Music Player'}</div><div class="trackArtist">Local playlist · external services below</div><input class="range" id="musicRange" type="range" min="0" max="100" value="0"><div class="playerBtns"><button class="circleBtn" id="musicPrev">◀</button><button class="circleBtn play" id="musicPlay">▶</button><button class="circleBtn" id="musicNext">▶</button></div><div class="playlist">${p.map((x,i)=>`<div class="song"><div><b>${esc(x.name)}</b><small>Local track</small></div><button class="btn small danger" data-music-del="${i}">Delete</button></div>`).join('')||'<div class="empty">Add songs to create your local playlist.</div>'}</div></div></div>`}
  function bindMusic(){let audio=window.__srsAudio||new Audio();window.__srsAudio=audio;$('#musicFile')?.addEventListener('change',e=>{[...e.target.files].forEach(f=>state.music.playlist.push({id:Date.now()+Math.random(),name:f.name,url:URL.createObjectURL(f)}));persist();renderRoute(false)});$('#musicPlay')?.addEventListener('click',()=>{if(!state.music.playlist[0])return notify('Add a local music file first');if(audio.src!==state.music.playlist[0].url)audio.src=state.music.playlist[0].url;audio.paused?audio.play():audio.pause()});$('#musicRange')?.addEventListener('input',e=>{if(audio.duration)audio.currentTime=audio.duration*(Number(e.target.value)/100)});audio.ontimeupdate=()=>{if($('#musicRange')&&audio.duration)$('#musicRange').value=String(Math.round(audio.currentTime/audio.duration*100))};
  }
  function renderSocial(){const n=state.notifications.filter(x=>!x.read).length;const slots=TOOLS['social-media'][3].map(a=>`<div class="miniTool"><b>${a}</b><small>${state.social?.connected?.[a]?'Connected':'Ready to connect'}</small><div class="heroActions"><button class="btn small primary" data-open-app="${esc(a)}" data-app-key="social-media">Open</button></div></div>`).join('');$('#content').innerHTML=header('Social Media','Platform hub with one place for launches and notifications.','<button class="btn primary" data-nav="notifications">Notifications</button>')+`<section class="workspace"><div class="workspaceCards">${slots}</div><div class="assignBox"><b>Live notification inbox:</b> ${n} unread. External platforms must be connected through their own OAuth/API; this website does not bypass their permissions.</div></section>`}
  function renderAI(){const slots=TOOLS['ai-tools'][3].map(a=>`<div class="miniTool"><b>${a}</b><small>Official platform launcher</small><div class="heroActions"><button class="btn small cyan" data-open-app="${esc(a)}" data-app-key="ai-tools">Open ${a}</button></div></div>`).join('');$('#content').innerHTML=header('AI Tools','Direct launch hub for AI platforms.','<button class="btn" data-add-app="ai-tools">＋ Add AI App</button>')+`<section class="workspace"><div class="workspaceCards">${slots}</div><div class="field" style="margin-top:12px"><label>Saved AI Prompt</label><textarea class="textarea" id="aiPrompt">${esc(state.workspaces['ai-tools']?.body||'')}</textarea><div class="autosave">✓ Saved automatically</div></div></section>`;$('#aiPrompt').addEventListener('input',()=>saveWorkspace('ai-tools',{body:$('#aiPrompt').value}))}
  function renderMoney(){const tr=state.finance.transfers||[];const latest=tr[0];$('#content').innerHTML=header('Money Transfer','Transparent transfer approval workflow for the SRS Vision team.','<button class="btn primary" data-new-transfer>＋ New Transfer Request</button>')+`<section class="workspace"><div class="assignBox"><b>Rule:</b> every transfer requires ${state.team.members.length}/${state.team.members.length} member approvals; one Deny blocks the request.</div>${latest?`<div class="workCard"><div class="workTitle">${esc(latest.recipient)} · ${money(latest.amount)}</div><div class="projectSub">Requested by ${esc(latest.requester)} · ${esc(latest.purpose||'No purpose')}</div><div class="transferList" style="margin-top:8px">${latest.approvals.map((a,i)=>`<div class="approval"><div><b>${esc(a.name)}</b><div class="projectSub">${a.decision||'Waiting'}</div></div><div class="heroActions"><button class="btn small green" data-approval="${i}" data-decision="Allow">Allow</button><button class="btn small danger" data-approval="${i}" data-decision="Deny">Deny</button></div></div>`).join('')}</div><div class="meta"><span class="chip">Status: ${esc(latest.status)}</span><span class="chip">Allowed: ${latest.approvals.filter(a=>a.decision==='Allow').length}/${state.team.members.length}</span></div>${latest.approvals.every(a=>a.decision==='Allow')?'<div class="pos"><b>✓ All members allowed. Ready for external bank/payment execution.</b></div>':'<div class="neg"><b>Transfer blocked until every member selects Allow.</b></div>'}</div>`:'<div class="empty">No transfer requests yet.</div>'}</section>`}
  function newTransfer(){openModal('New Transfer Request',`<div class="modalGrid"><div class="field"><label>Requester</label><select class="select" id="txRequester">${MEMBERS.map(n=>`<option>${n}</option>`).join('')}</select></div><div class="field"><label>Recipient / Account</label><input class="input" id="txRecipient"></div><div class="field"><label>Amount</label><input class="input" id="txAmount" type="number"></div><div class="field"><label>Purpose</label><input class="input" id="txPurpose"></div></div>`,()=>{const req=$('#txRequester').value,rec=$('#txRecipient').value.trim(),amt=Number($('#txAmount').value||0);if(!rec||!amt)throw new Error('Enter recipient and amount');state.finance.transfers.unshift({id:Date.now(),requester:req,recipient:rec,amount:amt,purpose:$('#txPurpose').value.trim(),status:'Pending',approvals:state.team.members.map(n=>({name:n,decision:null}))});state.notifications.unshift({id:Date.now()+1,title:'Transfer approval requested',body:`${req} requested ${money(amt)} for ${rec}.`,time:new Date().toISOString(),read:false});persist();closeModal();renderMoney();notify('Transfer request saved')})}
  function renderBanking(){const bs=state.finance.accounts;$('#content').innerHTML=header('Banking','Account balances, deposits, withdrawals and internal transactions.','<button class="btn primary" data-add-account>＋ Add Account</button>')+`<div class="accountGrid">${bs.map((b,i)=>`<div class="accountCard"><div>${esc(b.name)}</div><b>${money(b.balance)}</b><div class="projectSub">${esc(b.type)}</div><div class="heroActions"><button class="btn small" data-bank-action="${i}" data-kind="income">＋ Income</button><button class="btn small" data-bank-action="${i}" data-kind="expense">− Expense</button><button class="btn small primary" data-nav="money-transfer">💸 Transfer</button></div></div>`).join('')}</div><section class="panel" style="margin-top:12px"><div class="panelHead"><h3>Recent Transactions</h3></div><div class="panelBody">${state.finance.transactions.slice(0,12).map(t=>`<div class="event"><b class="${t.kind==='income'?'pos':'neg'}">${t.kind.toUpperCase()} · ${money(t.amount)}</b><small>${esc(t.note||'')} · ${esc(t.date||'')}</small></div>`).join('')||'<div class="empty">No transactions.</div>'}</div></section>`}
  function addAccount(){openModal('Add Bank Account',`<div class="modalGrid"><div class="field"><label>Account name</label><input class="input" id="baName"></div><div class="field"><label>Type</label><input class="input" id="baType" value="Business"></div><div class="field"><label>Opening balance</label><input class="input" id="baBal" type="number" value="0"></div></div>`,()=>{state.finance.accounts.push({id:'a'+Date.now(),name:$('#baName').value.trim()||'Bank Account',type:$('#baType').value.trim()||'Business',balance:Number($('#baBal').value||0)});persist();closeModal();renderBanking();notify('Bank account saved')})}
  function bankAction(i,kind){openModal(kind==='income'?'Add Income':'Add Expense',`<div class="field"><label>Amount</label><input class="input" id="faAmt" type="number"></div><div class="field"><label>Note</label><input class="input" id="faNote"></div>`,()=>{const amt=Number($('#faAmt').value||0);if(!amt)throw new Error('Enter amount');state.finance.accounts[i].balance += kind==='income'?amt:-amt;state.finance.transactions.unshift({id:Date.now(),kind,amount:amt,note:$('#faNote').value.trim(),date:new Date().toISOString().slice(0,10),account:state.finance.accounts[i].name});persist();closeModal();renderBanking();notify((kind==='income'?'Income':'Expense')+' saved')})}
  function renderAccounts(){const income=state.finance.transactions.filter(t=>t.kind==='income').reduce((s,x)=>s+Number(x.amount||0),0),expense=state.finance.transactions.filter(t=>t.kind==='expense').reduce((s,x)=>s+Number(x.amount||0),0),profit=income-expense;$('#content').innerHTML=header('Accounts','Finance summary and profit/loss overview.','<button class="btn primary" data-nav="banking">Open Banking</button>')+`<div class="graphGrid"><section class="graphBox"><div class="projectSub">Total Balance</div><div class="profitValue">${money(state.finance.accounts.reduce((s,x)=>s+Number(x.balance||0),0))}</div><div class="projectSub">Across ${state.finance.accounts.length} accounts</div></section><section class="graphBox"><div class="projectSub">Profit / Loss</div><div class="profitValue ${profit>=0?'pos':'neg'}">${money(profit)}</div><div class="projectSub">Income ${money(income)} · Expense ${money(expense)}</div></section></div><section class="panel" style="margin-top:12px"><div class="panelHead"><h3>Money movement graph</h3></div><div class="panelBody"><div class="barChart">${[20,35,40,54,67,72].map((v,i)=>`<div class="vcol"><i style="height:${v}%"></i><small>${['Apr','May','Jun','Jul','Aug','Sep'][i]}</small></div>`).join('')}</div></div></section>`}
  function renderNotifications(){const rows=state.notifications.map((n,i)=>`<div class="notifRow"><span class="notifIcon">🔔</span><div><b>${esc(n.title)}</b><small>${esc(n.body)} · ${new Date(n.time).toLocaleString('en-IN')}</small></div><button class="btn small" data-mark-read="${i}">${n.read?'Read':'Mark Read'}</button></div>`).join('');$('#content').innerHTML=header('Notifications','Project, task, social, finance and system notifications.','<button class="btn primary" data-test-notification>Test Notification</button>')+`<section class="panel"><div class="panelBody">${rows||'<div class="empty">No notifications.</div>'}</div></section>`}
  function renderFiles(){const rows=state.files.map((f,i)=>`<div class="event"><b>${esc(f.name)}</b><small>${esc(f.project||'General')} · ${esc(f.date||'')}</small><div class="heroActions"><button class="btn small danger" data-delete-file="${i}">Delete</button></div></div>`).join('');$('#content').innerHTML=header('Files','Project files and working documents are restored from browser storage.','<label class="btn primary">Upload File<input id="fileUpload" type="file" hidden></label>')+`<section class="panel"><div class="panelBody">${rows||'<div class="empty">No saved files.</div>'}</div></section>`;$('#fileUpload')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{state.files.unshift({id:Date.now(),name:f.name,type:f.type,size:f.size,date:new Date().toISOString().slice(0,10),data:r.result,project:'General'});persist();renderFiles();notify('File saved locally')};r.readAsDataURL(f)})}
  function renderSettings(){const q=state.settings;$('#content').innerHTML=header('Settings','SRS Vision appearance, backup and platform preferences.')+`<section class="workspace"><div class="modalGrid"><div class="field"><label>Company</label><input class="input" id="setCompany" value="${esc(q.company)}"></div><div class="field"><label>Sidebar quote</label><input class="input" id="setQuote" value="${esc(q.quote)}"></div></div><div class="heroActions"><button class="btn primary" id="saveSettings">Save Settings</button><button class="btn" id="exportBackup">Export Backup</button><button class="btn danger" id="resetLocal">Reset Local Data</button></div><div class="autosave" style="margin-top:8px">All page state is saved locally immediately and queued for Supabase synchronization.</div></section>`;$('#saveSettings').onclick=()=>{state.settings.company=$('#setCompany').value.trim()||'SRS VISION';state.settings.quote=$('#setQuote').value.trim()||'Create. Share. Grow.';persist();renderShell();renderRoute(false);notify('Settings saved')};$('#exportBackup').onclick=()=>downloadBlob(JSON.stringify(state,null,2),'application/json','srs-vision-backup.json');$('#resetLocal').onclick=()=>{if(confirm('Reset local SRS Vision data?')){state=makeInitial();persist();renderShell();renderRoute(false);notify('Local state reset')}}}
  function renderDatabase(){const pending=localStorage.getItem('srsVisionPending')==='1';$('#content').innerHTML=header('Database & Realtime','Connection diagnostics, manual sync and shared state health.','<button class="btn primary" id="dbReconnect">Reconnect</button>')+`<div class="kpis"><div class="kpi"><span>Connection</span><b id="dbLive">${Live.status==='online'?'LIVE':'LOCAL'}</b><span class="hint">${esc(Live.detail||'')}</span></div><div class="kpi"><span>Realtime</span><b id="dbRt">${Live.status==='online'?'ON':'OFF'}</b><span class="hint">Postgres Changes</span></div><div class="kpi"><span>Pending Save</span><b>${pending?'YES':'NO'}</b><span class="hint">Auto queue</span></div><div class="kpi"><span>Last Local Save</span><b style="font-size:14px">${esc(localStorage.getItem('srsVisionLastLocalSave')||'—')}</b></div></div><section class="panel"><div class="panelBody"><div class="assignBox"><b>Project:</b> pfpokabiphsyjkkkdslc.supabase.co<br><b>Table:</b> public.srs_vision_state<br><b>Auth:</b> Anonymous Sign-In<br><b>Behavior:</b> local save first → Supabase sync → realtime updates</div><div class="heroActions"><button class="btn cyan" id="dbSync">Sync Now</button><button class="btn" id="dbReload">Reload Shared Data</button><button class="btn" id="dbExport">Export Local Backup</button></div></div></section>`;$('#dbReconnect').onclick=()=>Live.init(true);$('#dbSync').onclick=()=>Live.write(true);$('#dbReload').onclick=async()=>{if(!Live.client)await Live.init(true);if(!Live.client)return notify('Supabase unavailable; local data kept');try{const r=await Live.client.from('srs_vision_state').select('data').eq('id',1).single();if(r.error)throw r.error;state=mergeState(r.data.data);saveLocal();renderRoute(false);notify('Shared data reloaded')}catch(e){notify('Reload failed: '+e.message)}};$('#dbExport').onclick=()=>downloadBlob(JSON.stringify(state,null,2),'application/json','srs-vision-local-backup.json')}
  function mergeState(raw){const b=makeInitial();if(!raw||typeof raw!=='object')return state;return {...b,...raw,team:{...b.team,...raw.team,members:Array.isArray(raw.team?.members)?raw.team.members:b.team.members},finance:{...b.finance,...raw.finance,accounts:Array.isArray(raw.finance?.accounts)?raw.finance.accounts:b.finance.accounts,transactions:Array.isArray(raw.finance?.transactions)?raw.finance.transactions:[],transfers:Array.isArray(raw.finance?.transfers)?raw.finance.transfers:[]},settings:{...b.settings,...raw.settings}}}
  function renderHub(){const cards=Object.entries(TOOLS).map(([r,v])=>`<button class="toolSlot" data-nav="${r}"><div class="toolIcon">${v[0]}</div><b>${esc(v[1])}</b><small>${esc(v[2])}</small></button>`).join('');$('#content').innerHTML=header('All Tool Slots','Choose a dedicated dashboard; tools never replace the main dashboard.')+`<section class="workspace"><div class="toolGrid">${cards}</div></section>`}
  function renderRoute(rerenderShell=true){if(rerenderShell)renderShell();renderStatus();if(route==='dashboard')return renderMain();if(route==='team')return renderTeam();if(route==='projects')return renderProjects();if(route==='calendar')return renderCalendar();if(route==='reports')return renderReports();if(route==='work')return renderWork();if(route==='notifications')return renderNotifications();if(route==='files')return renderFiles();if(route==='money-transfer')return renderMoney();if(route==='banking')return renderBanking();if(route==='accounts')return renderAccounts();if(route==='database')return renderDatabase();if(route==='settings')return renderSettings();if(route==='tools-hub')return renderHub();if(TOOLS[route]){renderTool(route);if(route==='music')bindMusic();return}replaceRoute('dashboard')}
  let modalSave=null;function ensureModal(){if($('#modal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="modalBox"><div class="modalHead"><h3 id="modalTitle">Edit</h3><button class="btn" id="modalClose">×</button></div><div id="modalBody"></div><div class="heroActions" style="justify-content:flex-end"><button class="btn ghost" id="modalCancel">Cancel</button><button class="btn primary" id="modalSave">Save</button></div></div></div>`);$('#modalClose').onclick=closeModal;$('#modalCancel').onclick=closeModal;$('#modalSave').onclick=()=>{try{modalSave?.()}catch(e){notify(e.message)}}}
  function openModal(title,html,save){ensureModal();$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;modalSave=save;$('#modal').classList.add('open')};function closeModal(){const m=$('#modal');if(m)m.classList.remove('open');modalSave=null}
  function downloadBlob(text,type,name){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}function printHtml(title,body){const w=window.open('','_blank','width=900,height=800');if(!w)return;w.document.write(`<html><head><title>${esc(title)}</title></head><body style="font:16px Arial;padding:40px"><h1>${esc(title)}</h1><div style="white-space:pre-wrap">${esc(body)}</div></body></html>`);w.document.close();setTimeout(()=>w.print(),200)}
  function addApp(key){openModal('Add App Slot',`<div class="field"><label>App Name</label><input class="input" id="appName"></div><div class="field"><label>URL</label><input class="input" id="appUrl" placeholder="https://example.com"></div>`,()=>{const name=$('#appName').value.trim(),url=$('#appUrl').value.trim();if(!name||!/^https?:\/\//i.test(url))throw new Error('Enter an app name and a valid https:// URL');state.apps[key]=state.apps[key]||[];state.apps[key].push({name,url});persist();closeModal();renderRoute(false);notify('Custom app slot added')})}
  function taskShare(id){const t=state.tasks.find(x=>x.id==id);if(!t)return;const msg=`SRS Vision Work\n${t.title}\nMember: ${t.member}\nTool: ${TOOLS[t.tool]?.[1]||t.tool}\nPrompt: ${t.prompt||''}`;openModal('Share Work',`<textarea class="textarea" id="shareWork">${esc(msg)}</textarea><div class="heroActions"><button class="btn green" id="wshare">WhatsApp</button><button class="btn primary" id="eshare">Email</button></div>`,()=>{});$('#wshare').onclick=()=>window.open('https://wa.me/?text='+encodeURIComponent($('#shareWork').value),'_blank','noopener');$('#eshare').onclick=()=>location.href='mailto:?subject='+encodeURIComponent('SRS Vision Work: '+t.title)+'&body='+encodeURIComponent($('#shareWork').value)}
  document.addEventListener('click',e=>{
    const n=e.target.closest?.('[data-nav]');if(n){e.preventDefault();pushRoute(n.dataset.nav);return}
    if(e.target.closest?.('[data-back]')){e.preventDefault();if(history.length>1)history.back();else pushRoute('dashboard');return}
    if(e.target.closest?.('[data-edit-project]')){projectModal(Number(e.target.closest('[data-edit-project]').dataset.editProject));return}
    if(e.target.closest?.('[data-assign-project]')){projectModal(Number(e.target.closest('[data-assign-project]').dataset.assignProject),true);return}
    if(e.target.closest?.('[data-share-project]')){shareProject(Number(e.target.closest('[data-share-project]').dataset.shareProject));return}
    if(e.target.closest?.('[data-continue-project]')){continueProject(Number(e.target.closest('[data-continue-project]').dataset.continueProject));return}
    if(e.target.closest?.('[data-add-project]')){projectModal();return}
    if(e.target.closest?.('[data-member-edit]')){editMember(Number(e.target.closest('[data-member-edit]').dataset.memberEdit));return}
    if(e.target.closest?.('[data-member-custom]')){const i=Number(e.target.closest('[data-member-custom]').dataset.memberCustom),m=state.team.members[i];openModal('Custom Member Data',`<div class="field"><label>Skills</label><input class="input" id="cs" value="${esc(m.skills)}"></div><div class="field"><label>Notes</label><textarea class="textarea" id="cn">${esc(m.notes)}</textarea></div>`,()=>{m.skills=$('#cs').value.trim();m.notes=$('#cn').value.trim();persist();closeModal();renderTeam();notify('Member custom data saved')});return}
    if(e.target.closest?.('[data-member-delete]')){const i=Number(e.target.closest('[data-member-delete]').dataset.memberDelete);if(confirm('Remove this SRS Vision member?')){state.team.members.splice(i,1);persist();renderTeam();notify('Member removed')}}
    if(e.target.closest?.('[data-add-member]')){openModal('Add SRS Vision Member',`<div class="modalGrid"><div class="field"><label>Name</label><input class="input" id="amName"></div><div class="field"><label>Role</label><input class="input" id="amRole" value="Team Member"></div><div class="field"><label>Service</label><input class="input" id="amService"></div><div class="field"><label>Phone</label><input class="input" id="amPhone"></div></div>`,()=>{const name=$('#amName').value.trim();if(!name)throw new Error('Enter a name');state.team.members.push({id:'m'+Date.now(),name,role:$('#amRole').value||'Team Member',service:$('#amService').value||'',phone:$('#amPhone').value||'',skills:'',notes:''});persist();closeModal();renderTeam();notify('Member added')});return}
    if(e.target.closest?.('[data-start-task]')){startTask(Number(e.target.closest('[data-start-task]').dataset.startTask));return}
    if(e.target.closest?.('[data-complete-task]')){const id=Number(e.target.closest('[data-complete-task]').dataset.completeTask),t=state.tasks.find(x=>x.id===id);if(t){t.status='Done';persist();renderRoute(false);notify('Work completed and saved')}}
    if(e.target.closest?.('[data-task-share]')){taskShare(Number(e.target.closest('[data-task-share]').dataset.taskShare));return}
    if(e.target.closest?.('[data-assign-work]')){assignWork();return}
    if(e.target.closest?.('[data-open-app]')){const b=e.target.closest('[data-open-app]'),name=b.dataset.openApp;window.open(APP_URLS[name]||'#','_blank','noopener');return}
    if(e.target.closest?.('[data-open-url]')){window.open(e.target.closest('[data-open-url]').dataset.openUrl,'_blank','noopener');return}
    if(e.target.closest?.('[data-add-app]')){addApp(e.target.closest('[data-add-app]').dataset.addApp);return}
    if(e.target.closest?.('[data-remove-app]')){const b=e.target.closest('[data-remove-app]');state.apps[b.dataset.removeApp]=(state.apps[b.dataset.removeApp]||[]).filter(a=>a.name!==b.dataset.removeName);persist();renderRoute(false);notify('App slot removed');return}
    if(e.target.closest?.('[data-music-del]')){state.music.playlist.splice(Number(e.target.closest('[data-music-del]').dataset.musicDel),1);persist();renderRoute(false);bindMusic();return}
    if(e.target.closest?.('[data-new-transfer]')){newTransfer();return}
    if(e.target.closest?.('[data-approval]')){const b=e.target.closest('[data-approval]');const i=Number(b.dataset.approval),d=b.dataset.decision,req=state.finance.transfers[0];if(!req)return;req.approvals[i].decision=d;req.status=req.approvals.some(a=>a.decision==='Deny')?'Blocked':req.approvals.every(a=>a.decision==='Allow')?'Approved':'Pending';state.notifications.unshift({id:Date.now(),title:'Transfer approval updated',body:`${req.approvals[i].name}: ${d}`,time:new Date().toISOString(),read:false});persist();renderMoney();return}
    if(e.target.closest?.('[data-add-account]')){addAccount();return}
    if(e.target.closest?.('[data-bank-action]')){const b=e.target.closest('[data-bank-action]');bankAction(Number(b.dataset.bankAction),b.dataset.kind);return}
    if(e.target.closest?.('[data-add-event]')){openModal('Add Calendar Event',`<div class="modalGrid"><div class="field"><label>Title</label><input class="input" id="evTitle"></div><div class="field"><label>Date</label><input class="input" id="evDate" type="date"></div><div class="field"><label>Time</label><input class="input" id="evTime" type="time"></div><div class="field"><label>Type</label><input class="input" id="evType" value="Custom"></div></div>`,()=>{state.calendar.push({id:Date.now(),title:$('#evTitle').value.trim()||'Event',date:$('#evDate').value||new Date().toISOString().slice(0,10),time:$('#evTime').value,type:$('#evType').value.trim()});persist();closeModal();renderCalendar();notify('Calendar event saved')});return}
    if(e.target.closest?.('[data-edit-event]')){const i=Number(e.target.closest('[data-edit-event]').dataset.editEvent),ev=state.calendar[i];openModal('Edit Event',`<div class="modalGrid"><div class="field"><label>Title</label><input class="input" id="eeTitle" value="${esc(ev.title)}"></div><div class="field"><label>Date</label><input class="input" id="eeDate" type="date" value="${esc(ev.date)}"></div><div class="field"><label>Time</label><input class="input" id="eeTime" type="time" value="${esc(ev.time||'')}"></div></div>`,()=>{ev.title=$('#eeTitle').value;ev.date=$('#eeDate').value;ev.time=$('#eeTime').value;persist();closeModal();renderCalendar();notify('Event updated')});return}
    if(e.target.closest?.('[data-delete-event]')){const i=Number(e.target.closest('[data-delete-event]').dataset.deleteEvent);if(confirm('Delete event?')){state.calendar.splice(i,1);persist();renderCalendar();notify('Event deleted')}}
    if(e.target.closest?.('[data-mark-read]')){const i=Number(e.target.closest('[data-mark-read]').dataset.markRead);state.notifications[i].read=true;persist();renderNotifications();return}
    if(e.target.closest?.('[data-test-notification]')){state.notifications.unshift({id:Date.now(),title:'SRS Vision test notification',body:'Notification center is working.',time:new Date().toISOString(),read:false});persist();renderNotifications();notify('Notification created');return}
    if(e.target.closest?.('[data-delete-file]')){const i=Number(e.target.closest('[data-delete-file]').dataset.deleteFile);if(confirm('Delete file?')){state.files.splice(i,1);persist();renderFiles();notify('File deleted')}}
    if(e.target.closest?.('[data-export-report]')){downloadBlob(JSON.stringify({company:'SRS VISION',generated:new Date().toISOString(),projects:state.projects,finance:state.finance},null,2),'application/json','srs-vision-report.json');return}
  });
  window.addEventListener('popstate',()=>{route=location.hash.slice(1)||'dashboard';renderShell();renderRoute(false)});window.addEventListener('hashchange',()=>{const r=location.hash.slice(1)||'dashboard';if(r!==route){route=r;renderShell();renderRoute(false)}});window.addEventListener('pagehide',()=>saveLocal());window.addEventListener('beforeunload',()=>saveLocal());
  document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveLocal();Live.write(true);notify('Saved')}});
  // ---------- Supabase single client ----------
  const Live={client:null,session:null,channel:null,status:'local',detail:'Auto-save enabled',timer:null,initPromise:null,writeChain:Promise.resolve(),
    async init(force=false){if(this.initPromise&&!force)return this.initPromise;this.initPromise=(async()=>{try{const cfg=window.SRS_VISION_CONFIG||{};if(!cfg.url||!cfg.publishableKey||!window.supabase){this.status='local';this.detail='Supabase config missing';renderStatus();return false;}if(!this.client)this.client=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});this.status='local';this.detail='Connecting…';renderStatus();let s=await this.client.auth.getSession();if(s.error)throw s.error;let ses=s.data?.session||null;if(!ses){const a=await this.client.auth.signInAnonymously();if(a.error)throw a.error;ses=a.data?.session||null}if(!ses)throw new Error('Anonymous session not returned');this.session=ses;try{await this.client.realtime.setAuth(ses.access_token)}catch{}const r=await this.client.from('srs_vision_state').select('data,updated_at').eq('id',1).maybeSingle();if(r.error)throw r.error;const remote=r.data?.data;if(remote&&Object.keys(remote).length){if(localStorage.getItem('srsVisionPending')==='1'){await this.write(true)}else{state=mergeState(remote);saveLocal()}}else{await this.write(true)}await this.subscribe();this.status='online';this.detail='Realtime ON';renderStatus();return true}catch(e){this.status='error';this.detail=e?.message||'Supabase connection failed';renderStatus();if(this.timer)clearTimeout(this.timer);this.timer=setTimeout(()=>this.init(true),5000);return false}finally{this.initPromise=null}})();return this.initPromise},
    async subscribe(){if(!this.client||!this.session)return false;if(this.channel){try{await this.client.removeChannel(this.channel)}catch{}}this.channel=this.client.channel('srs-vision-production-live').on('postgres_changes',{event:'*',schema:'public',table:'srs_vision_state',filter:'id=eq.1'},payload=>{if(!payload.new?.data||localStorage.getItem('srsVisionPending')==='1')return;state=mergeState(payload.new.data);saveLocal();renderRoute(false);notify('Live shared data updated')});return new Promise(resolve=>{let done=false;this.channel.subscribe((status,error)=>{if(status==='SUBSCRIBED'){done=true;resolve(true);return}if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'||status==='CLOSED'){this.status='error';this.detail=error?.message||'Realtime reconnecting…';renderStatus();if(!done){done=true;resolve(false)}}});setTimeout(()=>{if(!done){done=true;resolve(false)}},7000)})},
    write(force=false){const snap=clone(state);localStorage.setItem('srsVisionPending','1');this.writeChain=this.writeChain.then(async()=>{try{if(!this.client||!this.session)await this.init();if(!this.client||!this.session)throw new Error('Supabase unavailable; local save is safe');const row=await this.client.from('srs_vision_state').upsert({id:1,data:snap,updated_at:new Date().toISOString(),updated_by:this.session.user.id}).select('id').single();if(row.error)throw row.error;localStorage.removeItem('srsVisionPending');this.status='online';this.detail='Saved globally · realtime ON';renderStatus();return true}catch(e){localStorage.setItem('srsVisionPending','1');this.status='error';this.detail=e?.message||'Sync failed; local save preserved';renderStatus();if(!force&&this.timer){}setTimeout(()=>{if(localStorage.getItem('srsVisionPending')==='1')this.init(true)},4500);return false}});return this.writeChain}
  };window.SRSVisionLive=Live;
  ensureModal();renderShell();renderRoute(false);setTimeout(()=>Live.init(),250);
})();
