// SRS Vision final stability patch: deterministic navigation + single-write sync + database status dashboard.
(function(){
  'use strict';

  const specialRoutes = new Set([
    'dashboard','teams','graphic-design','ai-tools','video-tools','image-tools','document-tools','pdf-tools',
    'productivity-tools','developer-tools','business-tools','education-tools','entertainment-tools','utilities-tools',
    'social-media','notifications','money-transfer','database'
  ]);

  const oldGo = window.go;
  if(!window.__srsStableGoInstalled && typeof oldGo === 'function'){
    window.__srsStableGoInstalled = true;
    window.__srsUnderlyingGo = oldGo;
    window.go = function(route){
      if(!route) return;
      try{
        if(typeof section !== 'undefined') section = route;
      }catch(_e){}
      if(route === 'database') return window.renderDatabaseDashboard();
      return window.__srsUnderlyingGo(route);
    };
  }

  // Navigation generated by the core page uses the final stable router directly.
  const baseNav = window.nav;
  window.nav = function(){
    const items=[
      ['dashboard','⌂','Dashboard'],['clients','♙','Clients'],['projects','▣','Projects'],['history','◷','Projects History'],
      ['teams','♧','Teams'],['services','◈','Services'],['graphic-design','✦','Graphic Design'],['enquiries','▤','Enquiries'],
      ['partners','🤝','Partners'],['contacts','☎','Contacts'],['accounts','💰','Accounts'],['bank','🏦','Bank Accounts'],
      ['files','📁','Project Files'],['reports','▥','Reports'],['announcements','📢','Announcements'],['meetings','🤝','Team Meetings'],
      ['audit','🧾','Audit Trail'],['calendar','📅','Calendar'],['database','◉','Database']
    ];
    const el=document.getElementById('sidebar');
    if(!el) return typeof baseNav==='function' ? baseNav() : undefined;
    el.innerHTML=items.map(x=>`<button type="button" class="nav ${typeof section!=='undefined'&&section===x[0]?'active':''}" data-3fs-nav="${x[0]}"><span class="ico">${x[1]}</span>${x[2]}</button>`).join('');
    el.querySelectorAll('[data-3fs-nav]').forEach(btn=>btn.addEventListener('click',function(){window.go(this.dataset['3fsNav']);}));
    if(typeof window.syncSrsTopNav==='function') window.syncSrsTopNav();
  };

  window.go3FSSection = window.go;

  // Avoid duplicate queued network writes. persist() already emits 3fs:datachanged,
  // and live-db.js listens to that event; one save path is enough.
  if(typeof window.persist === 'function'){
    window.persistAndSync=function(){
      const changed=window.persist();
      try{window.nav();window.render();window.updatePermissionUI?.();window.updateNotifications?.();}catch(_e){}
      return changed;
    };
  }

  // Database dashboard gives a real health check and exact next-step messages.
  window.renderDatabaseDashboard=async function(){
    try{ if(typeof section!=='undefined') section='database'; }catch(_e){}
    if(typeof window.updateNotifications==='function') window.updateNotifications();
    const el=document.getElementById('content'); if(!el) return;
    el.innerHTML=`<div class="srsPlatform">
      <div class="srsTopline"><div><div class="srsEyebrow2">SRS VISION · DATABASE CONTROL</div><div class="srsTitle2">Database & Realtime</div><div class="srsSub2">Live connection, shared data health, and sync controls in one dedicated dashboard.</div></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="srsBack2" onclick="window.go('dashboard')">← Main Dashboard</button><button class="srsGlowBtn" id="srsDbCheckBtn">Check Connection</button></div></div>
      <section class="srsKpis2" id="srsDbKpis"><div class="srsKpi2"><span>Connection</span><b id="srsDbState">Checking…</b><small id="srsDbStateSub">Testing Supabase</small></div><div class="srsKpi2 purple"><span>Realtime</span><b id="srsDbRt">Checking…</b><small>Postgres Changes</small></div><div class="srsKpi2 cyan"><span>Server Update</span><b id="srsDbAt">—</b><small>Last shared-state write</small></div><div class="srsKpi2 pink"><span>Sync Queue</span><b id="srsDbQueue">0</b><small>Pending local changes</small></div></section>
      <div class="srsWorkspace2"><section class="srsPanel2"><div class="srsPanelHead2"><h2>Connection Health</h2><button id="srsDbReconnect">Reconnect →</button></div><div id="srsDbDetails" class="srsNotice2">Checking your Supabase project…</div><div class="srsLaunchGrid2" style="margin-top:12px"><button class="srsLaunch2" id="srsDbSync"><b>↻ Sync Now</b><small>Push pending changes and refresh the shared state.</small></button><button class="srsLaunch2" id="srsDbReload"><b>↺ Refresh Data</b><small>Read the latest server snapshot into this browser.</small></button><button class="srsLaunch2" id="srsDbLocal"><b>💾 Local Data</b><small>Keep working locally if the network is unavailable.</small></button><button class="srsLaunch2" id="srsDbExport"><b>⇩ Export Backup</b><small>Download the current SRS Vision data as JSON.</small></button></div></section>
      <section class="srsPanel2"><div class="srsPanelHead2"><h2>Required Supabase Setup</h2><span class="sub">Server-side</span></div><div class="srsChecklist2"><div class="srsCheck2 done"><span>✓</span>Browser-safe publishable key<small>Configured in supabase-config.js</small></div><div class="srsCheck2"><span>→</span>Anonymous Sign-Ins<small>Enable Anonymous provider in Supabase Authentication settings.</small></div><div class="srsCheck2"><span>→</span>Database schema<small>Run database.sql in the Supabase SQL Editor.</small></div><div class="srsCheck2"><span>→</span>Realtime publication<small>Ensure public.threefs_state is enabled for Realtime.</small></div><div class="srsCheck2"><span>→</span>RLS access<small>Allow authenticated anonymous sessions to read/write id = 1.</small></div></div></section></div>
      <div class="srsFooter2"><span>SRS Vision · Shared Database Control</span><span><span class="srsLive2" id="srsDbFooter">● Checking</span></span></div>
    </div>`;

    const check=async()=>{
      const state=document.getElementById('srsDbState'),sub=document.getElementById('srsDbStateSub'),rt=document.getElementById('srsDbRt'),at=document.getElementById('srsDbAt'),details=document.getElementById('srsDbDetails'),footer=document.getElementById('srsDbFooter');
      if(state)state.textContent='Checking…'; if(sub)sub.textContent='Testing Supabase'; if(details)details.textContent='Checking table access and realtime…'; if(footer)footer.textContent='● Checking';
      try{
        const h=await window.srsLiveHealth?.();
        const ok=!!h?.ok, st=h?.status||{};
        if(state)state.textContent=ok?'LIVE':'OFFLINE';
        if(sub)sub.textContent=ok?'Database reachable':'See details below';
        if(rt)rt.textContent=st.state==='online'?'ON':(ok?'READY':'OFF');
        if(at)at.textContent=h?.updated_at?new Date(h.updated_at).toLocaleString('en-IN'):'—';
        if(details){details.innerHTML=ok?`<b>Connected.</b><br>Supabase can read the shared state table and the Realtime client is ready. ${st.text||''}`:`<b>${esc(st.text||'Connection failed')}</b><br>${esc(st.details||'Check Anonymous Sign-Ins, database.sql, Realtime, and network access.')}`;}
        if(footer)footer.textContent=ok?'● Live database connected':'● Database unavailable';
      }catch(e){
        if(state)state.textContent='OFFLINE'; if(sub)sub.textContent='Health check failed'; if(rt)rt.textContent='OFF'; if(details)details.innerHTML=`<b>Database check failed.</b><br>${esc(String(e?.message||e))}`; if(footer)footer.textContent='● Database unavailable';
      }
      const q=localStorage.getItem('3fsPendingWrite')==='1'?1:0; const qel=document.getElementById('srsDbQueue');if(qel)qel.textContent=String(q);
    };
    document.getElementById('srsDbCheckBtn')?.addEventListener('click',check);
    document.getElementById('srsDbReconnect')?.addEventListener('click',async()=>{try{await window._3fsRefreshLive?.();}finally{check();}});
    document.getElementById('srsDbSync')?.addEventListener('click',async()=>{try{if(window._3fsPushLive&&window.store)await window._3fsPushLive(window.store,Object.keys(window.store));alert('Sync request queued.');}catch(e){alert('Sync could not be queued: '+(e?.message||e));}finally{check();}});
    document.getElementById('srsDbReload')?.addEventListener('click',async()=>{try{await window._3fsRefreshLive?.();alert('Refresh requested.');}catch(e){alert('Refresh failed: '+(e?.message||e));}finally{check();}});
    document.getElementById('srsDbLocal')?.addEventListener('click',()=>alert('Local browser data remains available as a fallback; it will be pushed when Supabase reconnects.'));
    document.getElementById('srsDbExport')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(window.store||{},null,2)],{type:'application/json'});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='srs-vision-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),500);});
    await check();
  };

  // Keep database dashboard from being eaten by old render overrides.
  const prevRender=window.render;
  window.render=function(){
    if(typeof section!=='undefined'&&section==='database'){window.renderDatabaseDashboard();return;}
    return typeof prevRender==='function'?prevRender.apply(this,arguments):undefined;
  };

  // Make the top database status control open the dedicated dashboard.
  document.addEventListener('click',function(e){const b=e.target.closest&&e.target.closest('#threefsSync');if(b){e.preventDefault();e.stopPropagation();window.go('database');}},true);

  // Give route buttons generated by the separate dashboards the same stable behavior.
  document.addEventListener('click',function(e){const el=e.target.closest&&e.target.closest('[data-srs-route]');if(el){e.preventDefault();window.go(el.getAttribute('data-srs-route'));}},true);
})();
